name: Java CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: sudo apt-get install openjdk-11-jdk-headless openjdk-11-doc ant ant-optional javacc junit4 libjline-java libjline-java-doc docbook-xsl-ns docbook-mathml docbook-xsl-saxon libxslthl-java sassc libxerces2-java graphviz
            - name: Build
              run: ant -noinput build
            - name: Test
              run: ant -noinput test
            - name: Deploy site
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: target/doc
