---

name: Java CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            ant{,-optional} \
            docbook-{xsl-{ns,saxon},mathml} \
            graphviz \
            javacc \
            junit4 \
            libjline-java{,-doc} \
            libxerces2-java \
            libxml-commons-resolver1.1-java \
            libxslthl-java \
            openjdk-11-{jdk-headless,doc} \
            python3-m2crypto \
            osc \
            sassc
      - name: Setup
        run: |
          git config tar.tar.xz.command 'xz -9'
      - name: Build
        run: |
          ant -v -noinput -Dlinux.flavour=debian build
          echo \
          '<html xmlns="http://www.w3.org/1999/xhtml">
          <head><meta http-equiv="refresh" content="0; url=html/"/></head>
          </html>' \
            >target/doc/index.xhtml
      - name: Test
        run: |
          ant -v -noinput -Dlinux.flavour=debian test
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
      - name: Commit to OBS
        env:
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}
        run: |
          ant -v -noinput -Dlinux.flavour=debian obs.commit
