name: Build and deploy site
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install dependencies
        run:
          sudo apt-get install openjdk-11-jdk-headless openjdk-11-doc ant ant-optional javacc junit4 libjline-java libjline-java-doc docbook-xsl-ns docbook-mathml docbook-xsl-saxon libxslthl-java sassc libxerces2-java graphviz
      - name: Build documentation
        run:
          ant docs
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
